import { Product } from "@/lib/types";

// 30+ products with real Unsplash images for premium meat
export const MOCK_PRODUCTS: Product[] = [
  // ─── BEEF ───────────────────────────────
  {
    id: "1", name: "Wagyu Ribeye Steak MB5+", slug: "wagyu-ribeye-mb5",
    description: "Our flagship Wagyu ribeye, marbled to perfection. Melt-in-your-mouth tenderness with rich, buttery flavour that sets the gold standard for premium beef.",
    category_id: "beef", category: { id: "beef", name: "Beef", slug: "beef", image_url: null, sort_order: 1 },
    price: 89.99, compare_at_price: 119.99,
    image_url: "https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80",
    images: ["https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80"],
    badge: "ALL-TIME FAVOURITE", badge_color: "red", in_stock: true, is_featured: true, is_best_seller: true,
    tags: ["wagyu", "steak", "beef", "premium"], weight_options: [{label:"300g",price:89.99},{label:"500g",price:139.99},{label:"1kg",price:259.99}],
    leanness_rating: 3, firmness_rating: 4, richness_rating: 9, created_at: new Date().toISOString(),
  },
  {
    id: "2", name: "Black Angus Tenderloin Fillet", slug: "angus-tenderloin",
    description: "The most tender cut of Black Angus beef. Lean, delicate, and perfect for a special occasion dinner.",
    category_id: "beef", category: { id: "beef", name: "Beef", slug: "beef", image_url: null, sort_order: 1 },
    price: 64.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80",
    images: [], badge: "NEW", badge_color: "green", in_stock: true, is_featured: true, is_best_seller: false,
    tags: ["angus", "steak", "beef", "tenderloin"], weight_options: [{label:"250g",price:64.99},{label:"500g",price:119.99}],
    leanness_rating: 8, firmness_rating: 6, richness_rating: 6, created_at: new Date().toISOString(),
  },
  {
    id: "3", name: "Premium Beef Mince 5-Star", slug: "beef-mince-5-star",
    description: "Freshly ground premium beef mince from Australian grass-fed cattle. Perfect for burgers, bolognese, and meatballs.",
    category_id: "beef", category: { id: "beef", name: "Beef", slug: "beef", image_url: null, sort_order: 1 },
    price: 18.99, compare_at_price: 24.99,
    image_url: "https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=800&q=80",
    images: [], badge: "BEST VALUE", badge_color: "green", in_stock: true, is_featured: false, is_best_seller: true,
    tags: ["mince", "beef", "family"], weight_options: [{label:"500g",price:18.99},{label:"1kg",price:35.99},{label:"2kg",price:64.99}],
    leanness_rating: 5, firmness_rating: 5, richness_rating: 6, created_at: new Date().toISOString(),
  },
  {
    id: "4", name: "Beef Short Ribs (Korean Style)", slug: "beef-short-ribs",
    description: "Cut thin flanken-style for fast grilling. Marinate and grill for the ultimate Korean BBQ experience at home.",
    category_id: "beef", category: { id: "beef", name: "Beef", slug: "beef", image_url: null, sort_order: 1 },
    price: 34.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    images: [], badge: "BBQ FAVOURITE", badge_color: "red", in_stock: true, is_featured: true, is_best_seller: true,
    tags: ["ribs", "beef", "bbq", "korean"], weight_options: [{label:"500g",price:34.99},{label:"1kg",price:64.99}],
    leanness_rating: 3, firmness_rating: 5, richness_rating: 8, created_at: new Date().toISOString(),
  },
  {
    id: "5", name: "T-Bone Steak 500g", slug: "t-bone-steak",
    description: "Classic T-bone from premium grain-fed beef. Two steaks in one — tenderloin and sirloin separated by the iconic T-shaped bone.",
    category_id: "beef", category: { id: "beef", name: "Beef", slug: "beef", image_url: null, sort_order: 1 },
    price: 42.99, compare_at_price: 54.99,
    image_url: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80",
    images: [], badge: null, badge_color: null, in_stock: true, is_featured: false, is_best_seller: true,
    tags: ["t-bone", "steak", "beef"], weight_options: [{label:"500g",price:42.99},{label:"700g",price:57.99}],
    leanness_rating: 5, firmness_rating: 6, richness_rating: 7, created_at: new Date().toISOString(),
  },
  // ─── LAMB ───────────────────────────────
  {
    id: "6", name: "Lamb Shoulder Chops Pack", slug: "lamb-shoulder-chops",
    description: "Thick-cut lamb shoulder chops with beautiful marbling. Ideal for slow cooking or BBQ grilling to achieve fork-tender results.",
    category_id: "lamb", category: { id: "lamb", name: "Lamb", slug: "lamb", image_url: null, sort_order: 2 },
    price: 29.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80",
    images: [], badge: "ALL-TIME FAVOURITE", badge_color: "red", in_stock: true, is_featured: true, is_best_seller: true,
    tags: ["lamb", "chops", "bbq"], weight_options: [{label:"500g",price:29.99},{label:"1kg",price:54.99}],
    leanness_rating: 4, firmness_rating: 6, richness_rating: 7, created_at: new Date().toISOString(),
  },
  {
    id: "7", name: "Lamb Rack – French Trimmed", slug: "lamb-rack-french",
    description: "Elegantly French-trimmed lamb rack for a restaurant-quality presentation. Season and roast for the ultimate dinner party centrepiece.",
    category_id: "lamb", category: { id: "lamb", name: "Lamb", slug: "lamb", image_url: null, sort_order: 2 },
    price: 54.99, compare_at_price: 69.99,
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    images: [], badge: "PREMIUM", badge_color: "red", in_stock: true, is_featured: true, is_best_seller: false,
    tags: ["lamb", "rack", "premium", "special-occasion"], weight_options: [{label:"600g",price:54.99},{label:"1.2kg",price:99.99}],
    leanness_rating: 5, firmness_rating: 6, richness_rating: 7, created_at: new Date().toISOString(),
  },
  {
    id: "8", name: "Lamb Leg Bone-In", slug: "lamb-leg-bone-in",
    description: "Full bone-in lamb leg, perfect for Sunday roasts. Slow-roast with rosemary, garlic and olive oil for unforgettable flavour.",
    category_id: "lamb", category: { id: "lamb", name: "Lamb", slug: "lamb", image_url: null, sort_order: 2 },
    price: 39.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=800&q=80",
    images: [], badge: "FAMILY PACK", badge_color: "green", in_stock: true, is_featured: false, is_best_seller: false,
    tags: ["lamb", "leg", "roast", "family"], weight_options: [{label:"1.5kg",price:39.99},{label:"2.5kg",price:59.99}],
    leanness_rating: 5, firmness_rating: 5, richness_rating: 7, created_at: new Date().toISOString(),
  },
  // ─── PORK ───────────────────────────────
  {
    id: "9", name: "Pork Belly Strips", slug: "pork-belly-strips",
    description: "Thick-cut pork belly strips with gorgeous fat layers. BBQ low and slow for crispy skin and melt-in-the-mouth meat.",
    category_id: "pork", category: { id: "pork", name: "Pork", slug: "pork", image_url: null, sort_order: 3 },
    price: 22.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    images: [], badge: "BBQ MUST-HAVE", badge_color: "red", in_stock: true, is_featured: true, is_best_seller: true,
    tags: ["pork", "belly", "bbq"], weight_options: [{label:"500g",price:22.99},{label:"1kg",price:39.99}],
    leanness_rating: 2, firmness_rating: 5, richness_rating: 9, created_at: new Date().toISOString(),
  },
  {
    id: "10", name: "Pork Spare Ribs Full Rack", slug: "pork-spare-ribs",
    description: "A full rack of meaty pork spare ribs. Low-and-slow BBQ heaven with a smoky glaze.",
    category_id: "pork", category: { id: "pork", name: "Pork", slug: "pork", image_url: null, sort_order: 3 },
    price: 32.99, compare_at_price: 44.99,
    image_url: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80",
    images: [], badge: null, badge_color: null, in_stock: true, is_featured: false, is_best_seller: true,
    tags: ["pork", "ribs", "bbq"], weight_options: [{label:"1kg",price:32.99},{label:"1.5kg",price:44.99}],
    leanness_rating: 3, firmness_rating: 5, richness_rating: 8, created_at: new Date().toISOString(),
  },
  {
    id: "11", name: "Pork Neck Collar Steak", slug: "pork-neck-collar",
    description: "The secret Thai BBQ cut — pork neck with beautiful fat marbling. Grill hot and fast for incredible results.",
    category_id: "pork", category: { id: "pork", name: "Pork", slug: "pork", image_url: null, sort_order: 3 },
    price: 19.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1606728035253-49e8a23146de?w=800&q=80",
    images: [], badge: "NEW", badge_color: "green", in_stock: true, is_featured: false, is_best_seller: false,
    tags: ["pork", "collar", "bbq"], weight_options: [{label:"500g",price:19.99}],
    leanness_rating: 3, firmness_rating: 6, richness_rating: 8, created_at: new Date().toISOString(),
  },
  // ─── CHICKEN ────────────────────────────
  {
    id: "12", name: "Chicken Maryland Pack", slug: "chicken-maryland",
    description: "Generous chicken maryland pieces (thigh + drumstick). Perfect for roasting, grilling, or slow cooking.",
    category_id: "chicken", category: { id: "chicken", name: "Chicken", slug: "chicken", image_url: null, sort_order: 4 },
    price: 16.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1598103442097-8b74394b95c7?w=800&q=80",
    images: [], badge: "FAMILY PACK", badge_color: "green", in_stock: true, is_featured: false, is_best_seller: true,
    tags: ["chicken", "maryland", "family"], weight_options: [{label:"1kg",price:16.99},{label:"2kg",price:29.99}],
    leanness_rating: 7, firmness_rating: 6, richness_rating: 5, created_at: new Date().toISOString(),
  },
  {
    id: "13", name: "Chicken Thigh Fillets Skinless", slug: "chicken-thigh-skinless",
    description: "Tender, juicy skinless chicken thigh fillets — the versatile protein for everyday cooking.",
    category_id: "chicken", category: { id: "chicken", name: "Chicken", slug: "chicken", image_url: null, sort_order: 4 },
    price: 14.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1604908177453-7462950a6a3b?w=800&q=80",
    images: [], badge: null, badge_color: null, in_stock: true, is_featured: false, is_best_seller: true,
    tags: ["chicken", "thigh", "skinless"], weight_options: [{label:"500g",price:14.99},{label:"1kg",price:27.99}],
    leanness_rating: 7, firmness_rating: 7, richness_rating: 5, created_at: new Date().toISOString(),
  },
  {
    id: "14", name: "Whole Free Range Chicken", slug: "whole-chicken",
    description: "Premium free-range whole chicken from Australian farms. Slow roast for crispy skin and flavourful, juicy meat.",
    category_id: "chicken", category: { id: "chicken", name: "Chicken", slug: "chicken", image_url: null, sort_order: 4 },
    price: 21.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=800&q=80",
    images: [], badge: "FREE RANGE", badge_color: "green", in_stock: true, is_featured: false, is_best_seller: false,
    tags: ["chicken", "whole", "free-range"], weight_options: [{label:"1.4kg",price:21.99},{label:"1.8kg",price:27.99}],
    leanness_rating: 7, firmness_rating: 7, richness_rating: 5, created_at: new Date().toISOString(),
  },
  // ─── BBQ PACKS ──────────────────────────
  {
    id: "15", name: "Ultimate BBQ Party Pack", slug: "ultimate-bbq-pack",
    description: "The perfect pack for your next gathering. Includes beef burgers, lamb chops, chicken wings, pork ribs, and snags — everything you need for an epic BBQ.",
    category_id: "bbq", category: { id: "bbq", name: "BBQ Packs", slug: "bbq", image_url: null, sort_order: 5 },
    price: 79.99, compare_at_price: 109.99,
    image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
    images: [], badge: "BEST SELLER", badge_color: "red", in_stock: true, is_featured: true, is_best_seller: true,
    tags: ["bbq", "pack", "party", "value"], weight_options: [{label:"3kg",price:79.99},{label:"5kg",price:119.99}],
    leanness_rating: 5, firmness_rating: 5, richness_rating: 7, created_at: new Date().toISOString(),
  },
  {
    id: "16", name: "Weekend BBQ Essentials Pack", slug: "weekend-bbq-pack",
    description: "A perfectly curated weekend BBQ pack for 4-6 people. Includes 4 rump steaks, 6 lamb cutlets, 1kg chicken wings, and 500g beef sausages.",
    category_id: "bbq", category: { id: "bbq", name: "BBQ Packs", slug: "bbq", image_url: null, sort_order: 5 },
    price: 54.99, compare_at_price: 74.99,
    image_url: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=800&q=80",
    images: [], badge: "ALL-TIME FAVOURITE", badge_color: "red", in_stock: true, is_featured: true, is_best_seller: true,
    tags: ["bbq", "pack", "weekend", "steak"], weight_options: [{label:"2.5kg",price:54.99}],
    leanness_rating: 5, firmness_rating: 5, richness_rating: 7, created_at: new Date().toISOString(),
  },
  {
    id: "17", name: "Family Grill Pack x8", slug: "family-grill-pack",
    description: "Feed the whole family with our value grill pack — 8 pieces of various cuts, all vacuum-sealed fresh.",
    category_id: "bbq", category: { id: "bbq", name: "BBQ Packs", slug: "bbq", image_url: null, sort_order: 5 },
    price: 44.99, compare_at_price: 59.99,
    image_url: "https://images.unsplash.com/photo-1565299715199-866c917206bb?w=800&q=80",
    images: [], badge: "FAMILY VALUE", badge_color: "green", in_stock: true, is_featured: false, is_best_seller: false,
    tags: ["bbq", "family", "grill", "value"], weight_options: [{label:"2kg",price:44.99}],
    leanness_rating: 5, firmness_rating: 5, richness_rating: 6, created_at: new Date().toISOString(),
  },
  // ─── WAGYU ──────────────────────────────
  {
    id: "18", name: "Wagyu Striploin MB9 200g", slug: "wagyu-striploin-mb9",
    description: "Extremely high marble score of 9. Intensely rich, buttery, and utterly extraordinary. A once-in-a-while indulgence.",
    category_id: "wagyu", category: { id: "wagyu", name: "Wagyu", slug: "wagyu", image_url: null, sort_order: 6 },
    price: 129.99, compare_at_price: 169.99,
    image_url: "https://images.unsplash.com/photo-1588347819613-eb49a508dedd?w=800&q=80",
    images: [], badge: "LUXURY", badge_color: "red", in_stock: true, is_featured: true, is_best_seller: false,
    tags: ["wagyu", "striploin", "luxury", "steak"], weight_options: [{label:"200g",price:129.99},{label:"400g",price:249.99}],
    leanness_rating: 1, firmness_rating: 4, richness_rating: 10, created_at: new Date().toISOString(),
  },
  {
    id: "19", name: "Wagyu Flat Iron Steak MB5", slug: "wagyu-flat-iron",
    description: "The value cut of Wagyu — incredible marbling and tenderness at a more accessible price point.",
    category_id: "wagyu", category: { id: "wagyu", name: "Wagyu", slug: "wagyu", image_url: null, sort_order: 6 },
    price: 59.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?w=800&q=80",
    images: [], badge: "NEW", badge_color: "green", in_stock: true, is_featured: true, is_best_seller: false,
    tags: ["wagyu", "flat-iron", "steak"], weight_options: [{label:"300g",price:59.99},{label:"500g",price:94.99}],
    leanness_rating: 3, firmness_rating: 5, richness_rating: 9, created_at: new Date().toISOString(),
  },
  // ─── SAUSAGES ───────────────────────────
  {
    id: "20", name: "Angus Beef Sausages 500g", slug: "angus-beef-sausages",
    description: "Thick-skin beef sausages made fresh from pure Black Angus mince. No fillers, no nasties.",
    category_id: "sausages", category: { id: "sausages", name: "Sausages", slug: "sausages", image_url: null, sort_order: 7 },
    price: 12.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1548366086-7f1b76106622?w=800&q=80",
    images: [], badge: "ALL-TIME FAVOURITE", badge_color: "red", in_stock: true, is_featured: false, is_best_seller: true,
    tags: ["sausages", "beef", "snags", "bbq"], weight_options: [{label:"500g",price:12.99},{label:"1kg",price:22.99}],
    leanness_rating: 5, firmness_rating: 5, richness_rating: 7, created_at: new Date().toISOString(),
  },
  {
    id: "21", name: "Lamb Merguez Sausages", slug: "lamb-merguez",
    description: "Spiced North African-style lamb sausages. Fragrant with cumin, coriander, and harissa. Incredible on the grill.",
    category_id: "sausages", category: { id: "sausages", name: "Sausages", slug: "sausages", image_url: null, sort_order: 7 },
    price: 14.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1515516969-d4008cc6241a?w=800&q=80",
    images: [], badge: "SPECIALTY", badge_color: "green", in_stock: true, is_featured: false, is_best_seller: false,
    tags: ["lamb", "sausages", "merguez", "specialty"], weight_options: [{label:"500g",price:14.99}],
    leanness_rating: 5, firmness_rating: 5, richness_rating: 7, created_at: new Date().toISOString(),
  },
  // ─── BURGERS ────────────────────────────
  {
    id: "22", name: "Wagyu Beef Burger Patties 4-Pack", slug: "wagyu-burger-patties",
    description: "Hand-formed Wagyu beef patties — 150g each. Just season with salt and pepper and cook for the best burgers of your life.",
    category_id: "burgers", category: { id: "burgers", name: "Burgers", slug: "burgers", image_url: null, sort_order: 8 },
    price: 29.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    images: [], badge: "MUST TRY", badge_color: "red", in_stock: true, is_featured: true, is_best_seller: true,
    tags: ["wagyu", "burger", "patties"], weight_options: [{label:"4-pack 600g",price:29.99},{label:"8-pack 1.2kg",price:54.99}],
    leanness_rating: 4, firmness_rating: 6, richness_rating: 8, created_at: new Date().toISOString(),
  },
  {
    id: "23", name: "Smash Burger Patties 6-Pack", slug: "smash-burger-patties",
    description: "Thin, smash-ready beef patties for the perfect crispy-edged smash burgers. 80g each — smash and stack!",
    category_id: "burgers", category: { id: "burgers", name: "Burgers", slug: "burgers", image_url: null, sort_order: 8 },
    price: 19.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80",
    images: [], badge: "TRENDING", badge_color: "green", in_stock: true, is_featured: false, is_best_seller: true,
    tags: ["burger", "smash", "patties"], weight_options: [{label:"6-pack",price:19.99}],
    leanness_rating: 4, firmness_rating: 6, richness_rating: 7, created_at: new Date().toISOString(),
  },
  // ─── MARINATED ──────────────────────────
  {
    id: "24", name: "Greek Lemon-Herb Lamb Cutlets", slug: "greek-lamb-cutlets-marinated",
    description: "Tender lamb cutlets, marinated overnight in lemon, garlic, oregano, and olive oil. Ready to grill in minutes.",
    category_id: "marinated", category: { id: "marinated", name: "Marinated", slug: "marinated", image_url: null, sort_order: 9 },
    price: 32.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1603048675614-1def26ee46a2?w=800&q=80",
    images: [], badge: "READY TO COOK", badge_color: "green", in_stock: true, is_featured: false, is_best_seller: false,
    tags: ["lamb", "marinated", "greek", "cutlets"], weight_options: [{label:"500g",price:32.99}],
    leanness_rating: 5, firmness_rating: 6, richness_rating: 6, created_at: new Date().toISOString(),
  },
  {
    id: "25", name: "Teriyaki Chicken Wings 1kg", slug: "teriyaki-chicken-wings",
    description: "Succulent chicken wings marinated in our house-made teriyaki sauce. Grill or oven bake for sticky, caramelised perfection.",
    category_id: "marinated", category: { id: "marinated", name: "Marinated", slug: "marinated", image_url: null, sort_order: 9 },
    price: 19.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&q=80",
    images: [], badge: "CROWD FAVOURITE", badge_color: "red", in_stock: true, is_featured: false, is_best_seller: true,
    tags: ["chicken", "wings", "teriyaki", "marinated"], weight_options: [{label:"1kg",price:19.99},{label:"2kg",price:35.99}],
    leanness_rating: 6, firmness_rating: 6, richness_rating: 6, created_at: new Date().toISOString(),
  },
  // ─── HALAL ──────────────────────────────
  {
    id: "26", name: "Halal Beef Shawarma Pack", slug: "halal-beef-shawarma",
    description: "Thinly sliced, pre-marinated halal beef shawarma strips. Authentic Middle Eastern spice blend. Ready to cook.",
    category_id: "halal", category: { id: "halal", name: "Halal", slug: "halal", image_url: null, sort_order: 10 },
    price: 24.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80",
    images: [], badge: "✅ HALAL", badge_color: "green", in_stock: true, is_featured: true, is_best_seller: true,
    tags: ["halal", "beef", "shawarma"], weight_options: [{label:"500g",price:24.99},{label:"1kg",price:44.99}],
    leanness_rating: 6, firmness_rating: 6, richness_rating: 6, created_at: new Date().toISOString(),
  },
  {
    id: "27", name: "Halal Lamb Kofta Mix 500g", slug: "halal-lamb-kofta",
    description: "Pre-seasoned halal lamb kofta mix. Shape onto skewers and grill for the perfect Middle Eastern feast.",
    category_id: "halal", category: { id: "halal", name: "Halal", slug: "halal", image_url: null, sort_order: 10 },
    price: 18.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    images: [], badge: "✅ HALAL", badge_color: "green", in_stock: true, is_featured: false, is_best_seller: false,
    tags: ["halal", "lamb", "kofta", "mince"], weight_options: [{label:"500g",price:18.99}],
    leanness_rating: 5, firmness_rating: 5, richness_rating: 7, created_at: new Date().toISOString(),
  },
  // ─── GIFT PACKS ─────────────────────────
  {
    id: "28", name: "The Steak Lover Gift Box", slug: "steak-lover-gift-box",
    description: "The ultimate gift for meat lovers. Includes 2x Wagyu Ribeye, 2x Angus Tenderloin, and 2x Premium Sirloin — all presented in premium vacuum-sealed packaging.",
    category_id: "gifts", category: { id: "gifts", name: "Gift Packs", slug: "gifts", image_url: null, sort_order: 11 },
    price: 149.99, compare_at_price: 199.99,
    image_url: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&q=80",
    images: [], badge: "GIFT READY", badge_color: "red", in_stock: true, is_featured: true, is_best_seller: false,
    tags: ["gift", "steak", "wagyu", "premium"], weight_options: [{label:"1.5kg",price:149.99}],
    leanness_rating: 4, firmness_rating: 5, richness_rating: 9, created_at: new Date().toISOString(),
  },
  // ─── MORE BEEF ──────────────────────────
  {
    id: "29", name: "Beef Cheeks Slow Braise Pack", slug: "beef-cheeks",
    description: "The ultimate slow-cook cut. Beef cheeks become impossibly tender and gelatinous after a long braise in red wine.",
    category_id: "beef", category: { id: "beef", name: "Beef", slug: "beef", image_url: null, sort_order: 1 },
    price: 27.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1611599537845-1c7aca0091c0?w=800&q=80",
    images: [], badge: "SLOW COOK", badge_color: "green", in_stock: true, is_featured: false, is_best_seller: false,
    tags: ["beef", "cheeks", "slow-cook"], weight_options: [{label:"500g",price:27.99},{label:"1kg",price:49.99}],
    leanness_rating: 4, firmness_rating: 3, richness_rating: 9, created_at: new Date().toISOString(),
  },
  {
    id: "30", name: "Premium Rump Steak 400g", slug: "rump-steak-400g",
    description: "Classic Aussie favourite — a thick-cut rump steak with bold beef flavour. Great value without compromising on taste.",
    category_id: "beef", category: { id: "beef", name: "Beef", slug: "beef", image_url: null, sort_order: 1 },
    price: 24.99, compare_at_price: 31.99,
    image_url: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80",
    images: [], badge: null, badge_color: null, in_stock: true, is_featured: false, is_best_seller: true,
    tags: ["rump", "steak", "beef", "value"], weight_options: [{label:"400g",price:24.99},{label:"600g",price:35.99}],
    leanness_rating: 6, firmness_rating: 7, richness_rating: 6, created_at: new Date().toISOString(),
  },
  {
    id: "31", name: "Oxtail Braising Pack", slug: "oxtail",
    description: "Collagen-rich oxtail pieces perfect for a hearty, deeply flavoured braise or stew. Slow cook for 4-6 hours.",
    category_id: "beef", category: { id: "beef", name: "Beef", slug: "beef", image_url: null, sort_order: 1 },
    price: 22.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1545093149-618ce3bcf49d?w=800&q=80",
    images: [], badge: null, badge_color: null, in_stock: true, is_featured: false, is_best_seller: false,
    tags: ["beef", "oxtail", "braise", "slow-cook"], weight_options: [{label:"1kg",price:22.99}],
    leanness_rating: 3, firmness_rating: 4, richness_rating: 9, created_at: new Date().toISOString(),
  },
  {
    id: "32", name: "Chicken Breast Fillets 1kg", slug: "chicken-breast-1kg",
    description: "Premium free-range chicken breast fillets — lean, versatile, and perfect for weeknight cooking.",
    category_id: "chicken", category: { id: "chicken", name: "Chicken", slug: "chicken", image_url: null, sort_order: 4 },
    price: 18.99, compare_at_price: null,
    image_url: "https://images.unsplash.com/photo-1604908177453-7462950a6a3b?w=800&q=80",
    images: [], badge: null, badge_color: null, in_stock: true, is_featured: false, is_best_seller: true,
    tags: ["chicken", "breast", "lean", "free-range"], weight_options: [{label:"1kg",price:18.99},{label:"2kg",price:34.99}],
    leanness_rating: 9, firmness_rating: 7, richness_rating: 4, created_at: new Date().toISOString(),
  },
];

export const MOCK_CATEGORIES = [
  { id: "beef", name: "Beef", slug: "beef", image_url: null, sort_order: 1 },
  { id: "lamb", name: "Lamb", slug: "lamb", image_url: null, sort_order: 2 },
  { id: "pork", name: "Pork", slug: "pork", image_url: null, sort_order: 3 },
  { id: "chicken", name: "Chicken", slug: "chicken", image_url: null, sort_order: 4 },
  { id: "bbq", name: "BBQ Packs", slug: "bbq", image_url: null, sort_order: 5 },
  { id: "wagyu", name: "Wagyu", slug: "wagyu", image_url: null, sort_order: 6 },
  { id: "sausages", name: "Sausages", slug: "sausages", image_url: null, sort_order: 7 },
  { id: "burgers", name: "Burgers", slug: "burgers", image_url: null, sort_order: 8 },
  { id: "marinated", name: "Marinated", slug: "marinated", image_url: null, sort_order: 9 },
  { id: "halal", name: "Halal", slug: "halal", image_url: null, sort_order: 10 },
  { id: "gifts", name: "Gift Packs", slug: "gifts", image_url: null, sort_order: 11 },
];
